version: 2.1

orbs:
  rn: react-native-community/react-native@4.4.2

jobs:
  checkout_code:
    executor: 
      name: rn/linux_js
      node_version: '10'
    steps:
      - checkout
      - persist_to_workspace:
          root: .
          paths: 
            - .
  install-dependencies:
    executor: 
      name: rn/linux_js
      node_version: '10'
    steps:
      - attach_workspace:
          at: .
      - restore_cache:
          keys:
            - dependencies-{{ .Environment.CACHE_VERSION }}-{{ checksum "package.json" }}
            - dependencies-
      - restore_cache:
          keys:
            - dependencies-example-{{ .Environment.CACHE_VERSION }}-{{ checksum "example/package.json" }}
            - dependencies-example-
      - run:
          name: Install dependencies
          command: |
            yarn install --cwd example --frozen-lockfile
            yarn install --frozen-lockfile
      - save_cache:
          key: dependencies-{{ .Environment.CACHE_VERSION }}-{{ checksum "package.json" }}
          paths: 
            - node_modules
      - save_cache:
          key: dependencies-example-{{ .Environment.CACHE_VERSION }}-{{ checksum "example/package.json" }}
          paths: 
            - example/node_modules
      - persist_to_workspace:
          root: .
          paths: 
            - .
  analyse:
    executor: 
      name: rn/linux_js
      node_version: '10'
    steps:
      - attach_workspace:
          at: .
      - run:
          name: Lint JS Code (ESLint)
          command: yarn run test:eslint
      - run:
          name: Flow
          command: yarn run test:flow
      # TODO: uncomment after adding jest tests
      # - run:
      #     name: Jest
      #     command: yarn run test:jest
      - run:
          name: Build Android JavaScript Bundle
          command: yarn run test:detox:android:bundle:release
      - run:
          name: Build iOS JavaScript Bundle
          command: yarn run test:detox:ios:bundle:release

workflows:
  test:
    jobs:
      - checkout_code
      - install-dependencies:
          requires:
            - checkout_code
      - analyse:
          requires:
            - install-dependencies
      - rn/android_build:
          name: build_android_debug
          project_path: "example/android"
          build_type: debug
          requires:
            - analyse
      - rn/android_build:
          name: build_android_release
          project_path: "example/android"
          build_type: release
          requires:
            - analyse
      - rn/android_test:
          detox_configuration: "android.emu.release"
          detox_loglevel: "trace"
          requires:
            - build_android_release
      - rn/ios_build_and_test:
          project_type: workspace
          project_path: "example/ios/ReactNativeImageEditorExample.xcworkspace"
          derived_data_path: "example/ios/build"
          pod_install_directory: "example/ios"
          device: "iPhone 11"
          build_configuration: "Debug"
          scheme: "ReactNativeImageEditorExample"
          detox_configuration: "ios.sim.debug"
          detox_loglevel: "trace"
          requires:
            - analyse